apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-scripts
  namespace: signature-forgery
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS signature_app_db;
    USE signature_app_db;
    
    CREATE TABLE IF NOT EXISTS users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(100) NOT NULL UNIQUE,
        password_hash VARCHAR(255) NOT NULL
    );

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: signature-forgery
type: Opaque
stringData:
  mysql-root-password: "rootpassword"
  mysql-user: "app_user"
  mysql-password: "app_password"

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: signature-forgery
spec:
  ports:
  - port: 3306
  selector:
    app: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: signature-forgery
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: signature_app_db
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-init-volume
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-init-volume
        configMap:
          name: mysql-init-scripts
